# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c744bb3c51b2ebe3150c80ac97ab1932d43ca7560dc725180a644c74eeb5e26b93a46962580868ac2a7b44dbf2911ad910d879db0dc0a06d459ebd76de00f8f5

test:
  secret_key_base: ace14173c55ab2e2f168ddc5bf2fb918af2edfbcd60c66a4dab70252a18cf7ccb99c2fd0939fde873d0175a3e518313c03c86d2ab7f67c95e13628b6770da476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
